import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const layout = await readFile(new URL('./layout.js', import.meta.url), 'utf8')
const nextConfig = await readFile(new URL('../next.config.js', import.meta.url), 'utf8')
const home = await readFile(new URL('./page.js', import.meta.url), 'utf8')
const homeClient = await readFile(new URL('./page.client.js', import.meta.url), 'utf8')
const methodology = await readFile(new URL('./methodology/page.js', import.meta.url), 'utf8')
const hypertrophyApp = await readFile(new URL('./hypertrophy-app/page.js', import.meta.url), 'utf8')
const blogIndexClient = await readFile(new URL('./blog/page.client.js', import.meta.url), 'utf8')
const blogRenderer = await readFile(new URL('./blog/[slug]/page.js', import.meta.url), 'utf8')
const blogPosts = await readFile(new URL('./blog/posts.js', import.meta.url), 'utf8')
const notFound = await readFile(new URL('./not-found.js', import.meta.url), 'utf8')
const progressArticle = await readFile(new URL('../content/blog/how-to-progress-gym-framework.md', import.meta.url), 'utf8')
const seoAudit = await readFile(new URL('../scripts/seo-audit.mjs', import.meta.url), 'utf8')
const sitemap = await readFile(new URL('./sitemap.xml/route.js', import.meta.url), 'utf8')
const apiSitemap = await readFile(new URL('./api/sitemap/route.js', import.meta.url), 'utf8')
const feed = await readFile(new URL('./api/feed/route.js', import.meta.url), 'utf8')
const search = await readFile(new URL('./api/search/route.js', import.meta.url), 'utf8')
const rpAlternatives = await readFile(new URL('../content/blog/alternatives-to-rp-hypertrophy-app.md', import.meta.url), 'utf8')
const rankingIosArticle = await readFile(new URL('../content/blog/best-hypertrophy-app-ios-review.md', import.meta.url), 'utf8')
const hypertrophyWorkoutAppArticle = await readFile(new URL('../content/blog/best-workout-app-hypertrophy-2026.md', import.meta.url), 'utf8')
const autoProgressionArticle = await readFile(new URL('../content/blog/auto-progression-feature-muscle-growth.md', import.meta.url), 'utf8')
const hypertrophyScienceArticle = await readFile(new URL('../content/blog/ultimate-science-muscle-hypertrophy-guide.md', import.meta.url), 'utf8')
const machinesArticle = await readFile(new URL('../content/blog/machines-vs-free-weights-2025-research.md', import.meta.url), 'utf8')
const supersetsArticle = await readFile(new URL('../content/blog/supersets-hypertrophy-science-2026.md', import.meta.url), 'utf8')
const bandsArticle = await readFile(new URL('../content/blog/resistance-bands-hypertrophy-muscle-growth-science.md', import.meta.url), 'utf8')
const myostatinArticle = await readFile(new URL('../content/blog/myostatin-muscle-growth-genetic-limits.md', import.meta.url), 'utf8')
const myoRepsArticle = await readFile(new URL('../content/blog/myo-reps-rest-pause-training-efficiency.md', import.meta.url), 'utf8')
const aiProgrammingArticle = await readFile(new URL('../content/blog/ai-fitness-programming-algorithms-2026.md', import.meta.url), 'utf8')

assert.ok(!layout.includes('record_sessions_percent:100'), 'public pages must not record 100% of sessions')
assert.ok(!layout.includes("'@type': 'FAQPage'"), 'FAQ schema must not be injected globally')
assert.ok(layout.includes("color: '#8f897c'"), 'footer text should meet contrast on the dark footer')
assert.ok(layout.includes('Surpass — Get Bigger On Purpose'), 'site title should match the current Surpass promise')
assert.ok(layout.includes('/surpass-icon.png'), 'sitewide icon links should use the Surpass brand asset')
assert.ok(nextConfig.includes("value: 'jacked-blog.vercel.app'"), 'legacy Vercel host should keep its canonical redirect')
assert.ok(nextConfig.includes("destination: 'https://jacked.coach/:path*'"), 'legacy Vercel redirect should preserve the requested path')
assert.ok(layout.includes('sizes="1024x1024"'), 'favicon link should expose a square Surpass icon size')
assert.ok(layout.includes('type="image/png"'), 'favicon link should expose a crawlable PNG type')

assert.ok(!home.includes('content/blog'), 'homepage should not read and hydrate the full article library')
assert.ok(home.includes('alternates'), 'homepage should define canonical metadata')

assert.ok(!homeClient.includes('ArticleLibrary'), 'homepage should keep the install path focused instead of hydrating the article library')
assert.ok(homeClient.includes('id="science"'), 'homepage should retain a focused science/library trust path')
assert.ok(homeClient.includes("'@type': 'FAQPage'"), 'homepage should expose its visible FAQ answers as page-level structured data')
assert.ok(layout.includes('href="/methodology"'), 'sitewide footer should expose the training methodology asset')
assert.ok(methodology.includes('Training Calculator Methodology'), 'methodology page should expose a descriptive SEO title')
assert.ok(methodology.includes("'@type': 'FAQPage'"), 'methodology page should expose its visible FAQs as structured data')
assert.ok(methodology.includes('privacy-safe web analytics'), 'methodology page should explain the privacy boundary in product language')
assert.ok(sitemap.includes("staticUrl('/methodology', 'monthly', '0.8')"), 'methodology page should be included in the XML sitemap')
assert.ok(apiSitemap.includes('https://jacked.coach/methodology'), 'legacy API sitemap should retain the methodology URL')
assert.ok(hypertrophyApp.includes('Hypertrophy App for iPhone'), 'hypertrophy acquisition page should target its commercial search intent')
assert.ok(hypertrophyApp.includes('seo_hypertrophy_app'), 'hypertrophy acquisition page should use a dedicated App Store campaign')
assert.ok(hypertrophyApp.includes("canonicalPath=\"/hypertrophy-app\""), 'hypertrophy acquisition page should expose its canonical schema path')
assert.ok(sitemap.includes("staticUrl('/hypertrophy-app', 'weekly', '0.95')"), 'hypertrophy acquisition page should be included in the XML sitemap')
assert.ok(apiSitemap.includes('https://jacked.coach/hypertrophy-app'), 'legacy API sitemap should retain the hypertrophy acquisition URL')

assert.ok(layout.includes('/blog/alternatives-to-rp-hypertrophy-app'), 'sitewide footer should link to the RP alternatives page')
assert.ok(homeClient.includes('/blog/alternatives-to-rp-hypertrophy-app'), 'homepage acquisition guides should link to the RP alternatives page')
assert.ok(sitemap.includes("post.slug === 'alternatives-to-rp-hypertrophy-app' ? '0.95'"), 'target RP alternatives page should get a sitemap priority bump')
assert.ok(blogPosts.includes('canonicalBlogPosts'), 'merged and legacy posts should expose a canonical discovery collection')
assert.ok(sitemap.includes('canonicalBlogPosts'), 'XML sitemap should exclude merged and legacy article URLs')
assert.ok(apiSitemap.includes('canonicalBlogPosts'), 'API sitemap should exclude merged and legacy article URLs')
assert.ok(feed.includes('canonicalBlogPosts'), 'RSS feed should not advertise merged and legacy article URLs')
assert.ok(search.includes('canonicalBlogPosts'), 'article search should not surface merged and legacy article URLs')
assert.ok(blogIndexClient.includes('className="library-map"'), 'blog index should expose a crawlable complete-library map')
assert.ok(blogIndexClient.includes('allPosts.map((post)'), 'complete-library map should link every canonical article')

assert.ok(blogRenderer.includes('#ranked-alternatives'), 'blog renderer should emit ranked alternatives schema when ranking items exist')
assert.ok(blogRenderer.includes("'@type': 'FAQPage'"), 'blog renderer should support article-level FAQ schema')
assert.ok(notFound.includes("title: { absolute: 'Page not found | Surpass' }"), '404 responses should not inherit the homepage title')
assert.ok(notFound.includes('data-global-cta="404_store"'), '404 should provide a measurable App Store recovery CTA')
assert.ok(progressArticle.includes('/blog/anabolic-resistance-older-adults-2026'), 'internal article links should resolve to the current anabolic-resistance slug')
assert.ok(seoAudit.includes("url.pathname.startsWith('/cdn-cgi/')"), 'SEO audit should ignore Cloudflare email-protection shims')
assert.ok(seoAudit.includes('non-html content-type='), 'SEO audit should keep image assets out of HTML metadata findings')
assert.ok(seoAudit.includes('hasRedirect'), 'SEO audit should classify redirect chains as redirects rather than merge findings')

assert.ok(rpAlternatives.includes('title: "Alternatives to RP Hypertrophy App (2026): Best Options for Serious Lifters"'), 'target article should keep exact-match RP alternatives title')
assert.ok(rpAlternatives.includes('keywords: "alternatives to RP Hypertrophy App'), 'target article should keep exact-match keyword metadata')
assert.ok(rpAlternatives.includes('rankingItems: "Surpass|Best overall alternative'), 'target article should keep ranked alternatives input data')
assert.ok(rpAlternatives.includes('RepLog|Best for lifters who want a lightweight RP alternative'), 'target article should cover RepLog as a direct SERP competitor')
assert.ok(rpAlternatives.includes('## RP Hypertrophy App Alternatives Comparison'), 'target article should include a direct alternatives comparison table')
assert.ok(rpAlternatives.includes('## Apps Like RP Hypertrophy App'), 'target article should cover apps-like-RP intent')
assert.ok(rpAlternatives.includes('## Where Each Alternative Beats RP'), 'target article should capture competitor comparison intent')
assert.ok(rpAlternatives.includes('## Who Should Stay With RP Hypertrophy App?'), 'target article should show balanced switching guidance')
assert.ok(rpAlternatives.includes('## RP Hypertrophy App Alternative for iPhone'), 'target article should capture iPhone alternative long-tail intent')
assert.ok(rpAlternatives.includes('## RP Hypertrophy App Free Alternative'), 'target article should capture free alternative long-tail intent')
assert.ok(rpAlternatives.includes('### What is the best RP Hypertrophy App alternative for iPhone?'), 'target article should keep iPhone FAQ for snippet coverage')
assert.ok(rpAlternatives.includes('[Best hypertrophy app for iOS](/blog/best-hypertrophy-app-ios-review)'), 'target article should link into the hypertrophy app cluster')
assert.ok(rankingIosArticle.includes('[alternatives to RP Hypertrophy App](/blog/alternatives-to-rp-hypertrophy-app)'), 'already-ranking iOS article should pass exact-query relevance to the RP alternatives page')
assert.ok(rankingIosArticle.includes('(/hypertrophy-app)'), 'iOS hypertrophy article should link to the dedicated product landing page')
assert.ok(hypertrophyWorkoutAppArticle.includes('(/hypertrophy-app)'), 'hypertrophy workout-app article should link to the dedicated product landing page')
assert.ok(autoProgressionArticle.includes('(/hypertrophy-app)'), 'auto-progression article should link to the dedicated product landing page')
assert.ok(hypertrophyScienceArticle.includes('[alternatives to RP Hypertrophy App](/blog/alternatives-to-rp-hypertrophy-app)'), 'authoritative hypertrophy guide should pass exact-query relevance to the RP alternatives page')
assert.ok(machinesArticle.includes('[alternatives to RP Hypertrophy App](/blog/alternatives-to-rp-hypertrophy-app)'), 'fresh crawled equipment article should pass exact-query relevance to the RP alternatives page')
assert.ok(supersetsArticle.includes('[alternatives to RP Hypertrophy App](/blog/alternatives-to-rp-hypertrophy-app)'), 'SERP-visible supersets article should pass exact-query relevance to the RP alternatives page')
assert.ok(bandsArticle.includes('[alternatives to RP Hypertrophy App](/blog/alternatives-to-rp-hypertrophy-app)'), 'SERP-visible resistance bands article should pass exact-query relevance to the RP alternatives page')
assert.ok(myostatinArticle.includes('[alternatives to RP Hypertrophy App](/blog/alternatives-to-rp-hypertrophy-app)'), 'SERP-visible myostatin article should pass exact-query relevance to the RP alternatives page')
assert.ok(myoRepsArticle.includes('[alternatives to RP Hypertrophy App](/blog/alternatives-to-rp-hypertrophy-app)'), 'SERP-visible myo-reps article should pass exact-query relevance to the RP alternatives page')
assert.ok(aiProgrammingArticle.includes('[alternatives to RP Hypertrophy App](/blog/alternatives-to-rp-hypertrophy-app)'), 'SERP-visible AI programming article should pass exact-query relevance to the RP alternatives page')

console.log('seo performance tests passed')
