import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

const layout = await readFile(new URL('./layout.js', import.meta.url), 'utf8')
const home = await readFile(new URL('./page.js', import.meta.url), 'utf8')
const homeClient = await readFile(new URL('./page.client.js', import.meta.url), 'utf8')
const blogRenderer = await readFile(new URL('./blog/[slug]/page.js', import.meta.url), 'utf8')
const sitemap = await readFile(new URL('./sitemap.xml/route.js', import.meta.url), 'utf8')
const rpAlternatives = await readFile(new URL('../content/blog/alternatives-to-rp-hypertrophy-app.md', import.meta.url), 'utf8')
const rankingIosArticle = await readFile(new URL('../content/blog/best-hypertrophy-app-ios-review.md', import.meta.url), 'utf8')
const hypertrophyScienceArticle = await readFile(new URL('../content/blog/ultimate-science-muscle-hypertrophy-guide.md', import.meta.url), 'utf8')
const machinesArticle = await readFile(new URL('../content/blog/machines-vs-free-weights-2025-research.md', import.meta.url), 'utf8')
const supersetsArticle = await readFile(new URL('../content/blog/supersets-hypertrophy-science-2026.md', import.meta.url), 'utf8')
const bandsArticle = await readFile(new URL('../content/blog/resistance-bands-hypertrophy-muscle-growth-science.md', import.meta.url), 'utf8')
const myostatinArticle = await readFile(new URL('../content/blog/myostatin-muscle-growth-genetic-limits.md', import.meta.url), 'utf8')
const myoRepsArticle = await readFile(new URL('../content/blog/myo-reps-rest-pause-training-efficiency.md', import.meta.url), 'utf8')
const aiProgrammingArticle = await readFile(new URL('../content/blog/ai-fitness-programming-algorithms-2026.md', import.meta.url), 'utf8')

assert.ok(!layout.includes('record_sessions_percent:100'), 'public pages must not record 100% of sessions')
assert.ok(!layout.includes("'@type': 'FAQPage'"), 'FAQ schema must not be injected globally')
assert.ok(layout.includes("color: '#8f897c'"), 'footer text should meet contrast on the dark footer')
assert.ok(layout.includes('Free Gym Workout Tracker with Weekly Muscle Targets'), 'site title should match the current workout tracker positioning')
assert.ok(layout.includes('/favicon-96x96.png'), 'Google-facing favicon should use an explicit 48px+ square icon')
assert.ok(layout.includes('sizes="96x96"'), 'favicon link should expose a Google-friendly square size')
assert.ok(layout.includes('type="image/png"'), 'favicon link should expose a crawlable PNG type')

assert.ok(!home.includes('content/blog'), 'homepage should not read and hydrate the full article library')
assert.ok(home.includes('alternates'), 'homepage should define canonical metadata')

assert.ok(!homeClient.includes('ArticleLibrary'), 'homepage should keep the install path focused instead of hydrating the article library')
assert.ok(homeClient.includes('id="science"'), 'homepage should retain a focused science/library trust path')

assert.ok(layout.includes('/blog/alternatives-to-rp-hypertrophy-app'), 'sitewide footer should link to the RP alternatives page')
assert.ok(homeClient.includes('/blog/alternatives-to-rp-hypertrophy-app'), 'homepage acquisition guides should link to the RP alternatives page')
assert.ok(sitemap.includes("post.slug === 'alternatives-to-rp-hypertrophy-app' ? '0.95'"), 'target RP alternatives page should get a sitemap priority bump')

assert.ok(blogRenderer.includes('#ranked-alternatives'), 'blog renderer should emit ranked alternatives schema when ranking items exist')
assert.ok(blogRenderer.includes("'@type': 'FAQPage'"), 'blog renderer should support article-level FAQ schema')

assert.ok(rpAlternatives.includes('title: "Alternatives to RP Hypertrophy App (2026): Best Options for Serious Lifters"'), 'target article should keep exact-match RP alternatives title')
assert.ok(rpAlternatives.includes('keywords: "alternatives to RP Hypertrophy App'), 'target article should keep exact-match keyword metadata')
assert.ok(rpAlternatives.includes('rankingItems: "Jacked|Best overall alternative'), 'target article should keep ranked alternatives input data')
assert.ok(rpAlternatives.includes('RepLog|Best for lifters who want a lightweight RP alternative'), 'target article should cover RepLog as a direct SERP competitor')
assert.ok(rpAlternatives.includes('## RP Hypertrophy App Alternatives Comparison'), 'target article should include a direct alternatives comparison table')
assert.ok(rpAlternatives.includes('## Apps Like RP Hypertrophy App'), 'target article should cover apps-like-RP intent')
assert.ok(rpAlternatives.includes('## Where Each Alternative Beats RP'), 'target article should capture competitor comparison intent')
assert.ok(rpAlternatives.includes('## Who Should Stay With RP Hypertrophy App?'), 'target article should show balanced switching guidance')
assert.ok(rpAlternatives.includes('## RP Hypertrophy App Alternative for iPhone'), 'target article should capture iPhone alternative long-tail intent')
assert.ok(rpAlternatives.includes('## RP Hypertrophy App Free Alternative'), 'target article should capture free alternative long-tail intent')
assert.ok(rpAlternatives.includes('### What is the best RP Hypertrophy App alternative for iPhone?'), 'target article should keep iPhone FAQ for snippet coverage')
assert.ok(rpAlternatives.includes('[Best hypertrophy app for iOS](/blog/best-hypertrophy-app-ios-review)'), 'target article should link into the hypertrophy app cluster')
assert.ok(rankingIosArticle.includes('[alternatives to RP Hypertrophy App](/blog/alternatives-to-rp-hypertrophy-app)'), 'already-ranking iOS article should pass exact-query relevance to the RP alternatives page')
assert.ok(hypertrophyScienceArticle.includes('[alternatives to RP Hypertrophy App](/blog/alternatives-to-rp-hypertrophy-app)'), 'authoritative hypertrophy guide should pass exact-query relevance to the RP alternatives page')
assert.ok(machinesArticle.includes('[alternatives to RP Hypertrophy App](/blog/alternatives-to-rp-hypertrophy-app)'), 'fresh crawled equipment article should pass exact-query relevance to the RP alternatives page')
assert.ok(supersetsArticle.includes('[alternatives to RP Hypertrophy App](/blog/alternatives-to-rp-hypertrophy-app)'), 'SERP-visible supersets article should pass exact-query relevance to the RP alternatives page')
assert.ok(bandsArticle.includes('[alternatives to RP Hypertrophy App](/blog/alternatives-to-rp-hypertrophy-app)'), 'SERP-visible resistance bands article should pass exact-query relevance to the RP alternatives page')
assert.ok(myostatinArticle.includes('[alternatives to RP Hypertrophy App](/blog/alternatives-to-rp-hypertrophy-app)'), 'SERP-visible myostatin article should pass exact-query relevance to the RP alternatives page')
assert.ok(myoRepsArticle.includes('[alternatives to RP Hypertrophy App](/blog/alternatives-to-rp-hypertrophy-app)'), 'SERP-visible myo-reps article should pass exact-query relevance to the RP alternatives page')
assert.ok(aiProgrammingArticle.includes('[alternatives to RP Hypertrophy App](/blog/alternatives-to-rp-hypertrophy-app)'), 'SERP-visible AI programming article should pass exact-query relevance to the RP alternatives page')

console.log('seo performance tests passed')
