export const APP_STORE_BASE = 'https://apps.apple.com/us/app/jacked/id6757132605'

export const toolGroups = [
  {
    title: 'Most useful between sets',
    items: ['next-set-calculator', 'rest-time-calculator', 'backoff-set-calculator', 'plate-calculator', 'rir-calculator'],
  },
  {
    title: 'Most useful before a workout',
    items: ['smart-warm-up-calculator', 'workout-split-builder', 'deload-calculator'],
  },
  {
    title: 'Most useful for planning',
    items: ['strength-level-calculator', 'weekly-volume-checker', 'one-rep-max-calculator', 'exercise-swap-finder', 'hevy-import-checker', 'strong-csv-import-checker', 'workout-csv-validator'],
  },
]

export const plannedTools = []

const coreTools = [
  {
    slug: 'next-set-calculator',
    type: 'next-set',
    name: 'Next Set Calculator',
    title: 'Next Set Calculator: What Weight Should I Lift Next?',
    metaDescription: 'Calculate your next set target from your last weight, reps, and RIR. Get a clear weight, rep target, and reason for your next workout.',
    h1: 'Next Set Calculator',
    promise: 'Enter your last set. Get your next target.',
    intro: 'Jacked uses your weight, reps, RIR, goal, and rep range to suggest what to lift next with a clear reason.',
    primaryKeyword: 'what weight should I lift next',
    campaign: 'next_set_calculator',
    defaults: {
      exercise: 'Bench press',
      units: 'kg',
      weight: 80,
      reps: 10,
      rir: 2,
      minReps: 8,
      maxReps: 10,
      targetRir: 2,
      goal: 'hypertrophy',
      increment: 2.5,
      equipment: 'barbell',
    },
    sections: [
      ['How Jacked chooses your next set', 'The calculator turns your completed reps plus RIR into effective reps to failure, estimates strength, then applies simple progression rules for your target rep range.'],
      ['When to add weight', 'Add load when you reach the top of the rep range without overshooting effort. If the target is 8-10 reps at 2 RIR and you hit 10 at 2 RIR, the next move is usually a small load increase.'],
      ['When to add reps instead', 'If you are inside the rep range and close to the target RIR, keep the same load and try to add one rep before increasing weight.'],
      ['When to hold the same weight', 'Hold load when the set was harder than planned, when RIR is unclear, or when the set is below the top of the range.'],
      ['How RIR changes progression', 'RIR separates a strong set from a desperate set. Ten reps with 2 RIR is a better signal for progression than ten reps at failure when the target was controlled effort.'],
      ['Common mistakes', 'Do not add weight just because a set felt good if reps are still below range. Do not reduce load after one off day unless reps and RIR both point down.'],
    ],
    examples: [
      'Last set: 80 kg x 10 @ 2 RIR. Target range: 8-10. Next target: 82.5 kg x 8-10 @ 2 RIR.',
      'Last set: 100 kg x 6 @ 1 RIR. Target range: 6-8. Next target: hold 100 kg and aim for 7 reps at cleaner effort.',
    ],
    faqs: [
      ['What should I lift next workout?', 'If you reached the top of your rep range at the planned RIR, add the smallest useful load jump. Otherwise, add reps or hold load.'],
      ['Is this a progressive overload calculator?', 'Yes, but it is decision-first: it tells you whether to add weight, add reps, hold, or reduce.'],
    ],
    related: ['rir-calculator', 'one-rep-max-calculator', 'plate-calculator', 'smart-warm-up-calculator'],
  },
  {
    slug: 'rir-calculator',
    type: 'rir',
    name: 'RIR Calculator',
    title: 'RIR Calculator: Convert Reps in Reserve Into Target Weight',
    metaDescription: 'Use weight, reps, and RIR to estimate your e1RM and calculate target loads for different reps and effort levels.',
    h1: 'RIR Calculator',
    promise: 'Convert reps in reserve into useful target weights.',
    intro: 'RPE is common in strength training. RIR is easier for many hypertrophy lifters: how many clean reps did you have left?',
    primaryKeyword: 'RIR calculator',
    campaign: 'rir_calculator',
    defaults: {
      exercise: 'Bench press',
      units: 'kg',
      weight: 100,
      reps: 5,
      rir: 1,
      targetReps: 8,
      targetRir: 2,
      goal: 'hypertrophy',
      increment: 2.5,
    },
    sections: [
      ['RIR to RPE conversion', 'RPE = 10 - RIR. RIR 0 is RPE 10, RIR 1 is RPE 9, RIR 2 is RPE 8, and RIR 3 is RPE 7.'],
      ['Why use RIR for hypertrophy?', 'RIR keeps the focus on repeatable hard sets. You can train close enough to failure without turning every set into a max-effort test.'],
      ['How target weights are estimated', 'The tool estimates e1RM from your recent set, then calculates the load that matches your target reps and target RIR.'],
      ['Common mistakes', 'RIR is only useful when reps are clean and range of motion is consistent. Treat uncertain RIR as lower-confidence data.'],
    ],
    examples: [
      '100 kg x 5 @ 1 RIR gives a useful target around 87.5 kg x 8 @ 2 RIR.',
      '80 kg x 10 @ 3 RIR can become a controlled hypertrophy target around 82.5 kg x 8 @ 2 RIR.',
    ],
    faqs: [
      ['How do I convert RIR to RPE?', 'Subtract RIR from 10. For example, 2 RIR equals RPE 8.'],
      ['Is RIR better than RPE?', 'Neither is magic. RIR is often simpler for hypertrophy because it asks how many clean reps were left.'],
    ],
    related: ['next-set-calculator', 'one-rep-max-calculator', 'smart-warm-up-calculator'],
  },
  {
    slug: 'one-rep-max-calculator',
    type: 'one-rm',
    name: '1RM Calculator',
    title: '1RM Calculator: Estimate Your One Rep Max From Reps and RIR',
    metaDescription: 'Estimate your one-rep max from weight, reps, and optional RIR. Includes percentage chart, rep maxes, and training targets.',
    h1: '1RM Calculator',
    promise: 'Estimate your max, then get a useful training target.',
    intro: 'Most 1RM calculators stop at the max estimate. Jacked also gives a practical next target for training.',
    primaryKeyword: '1RM calculator',
    campaign: 'one_rep_max_calculator',
    defaults: {
      exercise: 'Squat',
      units: 'kg',
      weight: 100,
      reps: 5,
      rir: 1,
      formula: 'jacked',
      increment: 2.5,
    },
    sections: [
      ['What is e1RM?', 'Estimated one-rep max is a ballpark strength estimate from a submaximal set. It is useful for trends and targets, not a perfect prediction.'],
      ['1RM vs PR', 'A 1RM is a max estimate or test. A PR is what you have actually achieved. Jacked treats estimates as training context.'],
      ['Why RIR improves the estimate', 'A set of five with three reps left is not the same as a set of five at failure. RIR lets the formula account for effort.'],
      ['Best rep ranges for estimating 1RM', 'Sets around 3-10 reps with clear effort usually produce better estimates than very high-rep sets.'],
      ['How to use e1RM for hypertrophy', 'Use e1RM to pick sensible rep-range loads, then let performance and RIR decide the next jump.'],
    ],
    examples: [
      '100 kg x 5 @ 1 RIR estimates around 117.5 kg e1RM and suggests about 87.5 kg x 8 @ 2 RIR.',
      '80 kg x 10 @ 2 RIR estimates around 114 kg e1RM, but the next useful target may still be a small rep-range progression.',
    ],
    faqs: [
      ['Which 1RM formula should I use?', 'The Jacked average uses Epley and Brzycki when valid. You can also view Epley, Brzycki, or Lander directly.'],
      ['Can I use this for bench, squat, and deadlift?', 'Yes. Exercise-specific pages can add better examples, but the calculator works for any lift.'],
    ],
    related: ['next-set-calculator', 'rir-calculator', 'plate-calculator'],
  },
  {
    slug: 'strength-level-calculator',
    type: 'strength-level',
    name: 'Strength Level Calculator',
    title: 'Strength Level Calculator: Compare Your Lift by Bodyweight',
    metaDescription: 'Estimate your strength level from exercise, sex, age, bodyweight, weight, reps, and RIR. See the next benchmark and what to train next.',
    h1: 'Strength Level Calculator',
    promise: 'Compare a lift by bodyweight and get the next benchmark.',
    intro: 'Enter a recent set to estimate your 1RM, see where the lift sits, and get the gap to the next practical strength tier.',
    primaryKeyword: 'strength level calculator',
    campaign: 'strength_level_calculator',
    defaults: {
      exercise: 'Bench press',
      units: 'kg',
      sex: 'male',
      age: 29,
      bodyweight: 82,
      liftWeight: 100,
      reps: 5,
      rir: 1,
      increment: 2.5,
    },
    sections: [
      ['How the strength level is calculated', 'The tool estimates 1RM from your set, divides it by bodyweight, then compares that ratio with transparent Jacked standards for the selected lift and sex.'],
      ['Why this is not a leaderboard', 'These tiers are practical training references. They are not federation records, medical categories, or copied user-population tables.'],
      ['How to use the next benchmark', 'Use the gap to decide whether the next block should chase load, reps, technique consistency, or a closer variation.'],
      ['When the result is lower confidence', 'High-rep sets, unclear RIR, shortened range of motion, and unusual equipment setups make strength comparisons noisier.'],
      ['Common mistakes', 'Do not change depth, grip, pause, range, or machine setup and treat the new number as the same lift.'],
    ],
    examples: [
      'Bench press: 100 kg x 5 @ 1 RIR at 82 kg bodyweight estimates a 117.5 kg 1RM and lands around Intermediate.',
      'Squat: a small gap to the next tier is a reason to run a focused block. A large gap is a reason to build reps and technique first.',
    ],
    faqs: [
      ['Is this like Strength Level?', 'It answers the same kind of question: how strong is this lift relative to bodyweight. Jacked adds RIR, confidence, and a next training action.'],
      ['Are these official strength standards?', 'No. They are practical Jacked standards for training decisions, not official competitive rankings.'],
      ['Should I chase the next level every workout?', 'No. Use the next level as a block-level target, then progress with normal sets, RIR, and recovery.'],
    ],
    related: ['one-rep-max-calculator', 'next-set-calculator', 'rir-calculator', 'plate-calculator'],
  },
  {
    slug: 'plate-calculator',
    type: 'plates',
    name: 'Plate Calculator',
    title: 'Plate Calculator: Work Out What Plates to Load',
    metaDescription: 'Enter your target weight, bar weight, and available plates. Get exactly what to load on each side.',
    h1: 'Plate Calculator',
    promise: 'Enter a target weight and load the bar fast.',
    intro: 'Use this between sets: target load in, plates per side out. Jacked shows this beside target loads inside the workout.',
    primaryKeyword: 'plate calculator',
    campaign: 'plate_calculator',
    defaults: {
      units: 'kg',
      targetWeight: 82.5,
      barWeight: 20,
      collarsEach: 0,
      plates: '25,20,15,10,5,2.5,1.25',
      loadStyle: 'balanced',
    },
    sections: [
      ['How the plate calculator works', 'The calculator subtracts the bar and collars, splits the remaining load across both sides, then loads available plates from large to small.'],
      ['Fewest plates vs common plates', 'Fewest plates minimizes the number of plates. Common plates avoids awkward combinations when a more familiar loading pattern is available.'],
      ['When the exact weight is not possible', 'Use the nearest possible load and keep the training decision consistent. A tiny rounding difference matters less than repeatable logging.'],
    ],
    examples: [
      'Target: 82.5 kg. Bar: 20 kg. Load each side: 20 kg + 10 kg + 1.25 kg.',
      'Target: 225 lb. Bar: 45 lb. Load each side: 45 lb + 45 lb.',
    ],
    faqs: [
      ['Does the bar weight count?', 'Yes. Target total weight includes the bar, plates, and collars.'],
      ['Can I enter custom plates?', 'Yes. Add comma-separated plates that match your gym or home setup.'],
    ],
    related: ['next-set-calculator', 'one-rep-max-calculator', 'smart-warm-up-calculator'],
  },
  {
    slug: 'smart-warm-up-calculator',
    type: 'warmup',
    name: 'Smart Warm-Up Calculator',
    title: 'Smart Warm-Up Calculator for Lifting',
    metaDescription: 'Generate warm-up sets from your target weight, exercise type, and recent training. Built for strength and hypertrophy workouts.',
    h1: 'Smart Warm-Up Calculator',
    promise: 'Generate warm-up sets from your working weight.',
    intro: 'Warm up enough to perform, not so much that the warm-up becomes the workout.',
    primaryKeyword: 'warm up set calculator',
    campaign: 'smart_warm_up_calculator',
    defaults: {
      exercise: 'Squat',
      movementType: 'squat',
      units: 'kg',
      targetWeight: 125,
      targetReps: 8,
      increment: 2.5,
      lastExposure: '8+ days',
      status: 'normal',
      preference: 'standard',
    },
    sections: [
      ['How the warm-up calculator works', 'Heavy compound lifts get more ramping sets. Isolation lifts get fewer. Recent exposure, soreness, caution, and preference can add or remove sets.'],
      ['Heavy compound warm-ups', 'A common path is about 40% x 8, 60% x 5, 75% x 3, then 85-90% x 1 before working sets.'],
      ['Isolation warm-ups', 'Most isolation lifts only need one or two warm-ups unless the load is unusually heavy or the joint needs extra preparation.'],
      ['Common mistakes', 'Do not turn warm-ups into grinders. Keep them crisp, leave reps in reserve, and save effort for working sets.'],
    ],
    examples: [
      'Squat target: 125 kg x 6-8. Warm up with 50 x 8, 75 x 5, 95 x 3, 112.5 x 1.',
      'Lateral raise target: 12.5 kg x 12-16. One lighter set is usually enough.',
    ],
    faqs: [
      ['How many warm-up sets should I do?', 'Enough to make the working weight feel familiar without creating fatigue. Heavy compounds usually need more than isolation lifts.'],
      ['Should warm-ups be close to failure?', 'No. Warm-ups should prepare the movement and joints while preserving effort for working sets.'],
    ],
    related: ['next-set-calculator', 'plate-calculator', 'rir-calculator'],
  },
  {
    slug: 'weekly-volume-checker',
    type: 'volume',
    name: 'Weekly Volume Checker',
    title: 'Weekly Training Volume Checker for Hypertrophy',
    metaDescription: 'Check your weekly hard sets by muscle group and see whether your training volume looks low, productive, or hard to recover from.',
    h1: 'Weekly Training Volume Checker',
    promise: 'Check hard sets by muscle and get one next action.',
    intro: 'Most volume advice is static. Jacked turns your weekly set counts into a practical coach readout.',
    primaryKeyword: 'weekly set volume calculator',
    campaign: 'weekly_volume_checker',
    defaults: {
      chest: 14,
      back: 18,
      quads: 10,
      hamstrings: 5,
      glutes: 8,
      sideDelts: 12,
      rearDelts: 6,
      biceps: 8,
      triceps: 8,
      calves: 4,
      abs: 4,
      trainingAge: 'intermediate',
      goal: 'hypertrophy',
      recovery: 'normal',
      performanceTrend: 'up',
      soreness: 'normal',
    },
    sections: [
      ['How to count hard sets', 'Count working sets taken close enough to failure to create a training signal. Warm-ups and very easy technique sets usually do not count.'],
      ['Low, productive, and high volume', 'The checker uses practical ranges based on training age, goal, and recovery. It does not diagnose your perfect volume.'],
      ['Why performance trend matters', 'High volume with improving performance is different from high volume with missed targets and high soreness.'],
      ['Common mistakes', 'Do not add sets everywhere at once. Add volume to the clearest low muscle first and watch performance for one to two weeks.'],
    ],
    examples: [
      'Chest: 16 sets, productive. Hamstrings: 4 sets, likely low. Next action: add 1-2 hamstring sets before adding more chest work.',
      'Back: 22 sets with poor recovery can be hard to recover from even if the number looks impressive.',
    ],
    faqs: [
      ['How many sets per muscle per week?', 'Many lifters grow well around 6-16 hard sets, but the useful range changes with training age, recovery, exercise selection, and effort.'],
      ['Is this medical advice?', 'No. It is a practical training check, not a diagnosis.'],
    ],
    related: ['deload-calculator', 'workout-split-builder', 'next-set-calculator'],
  },
  {
    slug: 'deload-calculator',
    type: 'deload',
    name: 'Deload Calculator',
    title: 'Deload Calculator: Should You Train, Reduce Volume, or Deload?',
    metaDescription: 'Answer a few training questions and get a practical recommendation: train normally, reduce volume, or deload.',
    h1: 'Deload Calculator',
    promise: 'Decide whether to train, reduce volume, or deload.',
    intro: 'Use recent performance, missed targets, soreness, joint discomfort, sleep, motivation, and stress to get a practical training decision.',
    primaryKeyword: 'do I need a deload',
    campaign: 'deload_calculator',
    defaults: {
      weeksSinceDeload: 6,
      performance: 'flat',
      missedTargets: '2+ workouts',
      soreness: 'high',
      jointDiscomfort: 'none',
      sleep: 'normal',
      motivation: 'normal',
      stress: 'normal',
    },
    sections: [
      ['How the deload calculator works', 'The tool scores recent fatigue signals. Stronger performance drops, repeated missed targets, poor sleep, high stress, and joint discomfort push the recommendation toward reducing work.'],
      ['When to train normally', 'If performance is improving and soreness, sleep, and stress are normal, keep training and avoid changing too many variables.'],
      ['When to reduce volume', 'Reduce volume when performance is flat or down and fatigue signals are stacking up, but you are not dealing with significant pain or injury.'],
      ['When to deload', 'Deload when multiple signals are red at once or joint discomfort is significant. Keep movement patterns and cut fatigue.'],
    ],
    examples: [
      'Performance flat, soreness high, missed targets in two sessions: reduce volume this week.',
      'Performance down, poor sleep, high stress, and 9 weeks since deload: deload this week.',
    ],
    faqs: [
      ['How often should I deload?', 'Many lifters do better with reactive deloads based on performance and fatigue rather than a fixed calendar.'],
      ['What if I have pain?', 'Pain, injury, or persistent symptoms should be handled with a qualified professional.'],
    ],
    related: ['weekly-volume-checker', 'smart-warm-up-calculator', 'next-set-calculator'],
  },
  {
    slug: 'workout-split-builder',
    type: 'split',
    name: 'Workout Split Builder',
    title: 'Workout Split Builder for Strength and Hypertrophy',
    metaDescription: 'Build a practical workout split from your training days, goal, equipment, and session length.',
    h1: 'Workout Split Builder',
    promise: 'Build a practical split from your constraints.',
    intro: 'Pick days, goal, equipment, session length, experience, and muscle focus. Get a split you can run inside Jacked.',
    primaryKeyword: 'workout split builder',
    campaign: 'workout_split_builder',
    defaults: {
      days: 4,
      goal: 'hypertrophy',
      sessionLength: '60',
      equipment: 'commercial gym',
      experience: 'intermediate',
      focus: 'chest',
    },
    sections: [
      ['How the split builder works', 'The builder chooses a split that fits your number of training days, then builds each training day with exercises, sets, reps, rest targets, weekly volume, equipment, and focus muscle adjustments.'],
      ['Why session length matters', 'A 45-minute session needs fewer exercises and cleaner priorities than a 75-minute session, so the builder trims accessories before it cuts the main work.'],
      ['Best split by training days', 'Two to three days usually favors full body. Four days usually fits upper/lower. Five to six days can support hybrid or push/pull/legs splits.'],
      ['Common mistakes', 'Do not pick a split because it looks advanced. Pick the split you can recover from and repeat.'],
    ],
    examples: [
      '4 days, hypertrophy, commercial gym: Upper / Lower with each major muscle trained twice weekly.',
      '3 days, 45 minutes: Full body beats a cramped body-part split for most lifters.',
    ],
    faqs: [
      ['What is the best workout split?', 'The best split is the one that fits your schedule, recovery, equipment, and target muscles.'],
      ['Can I build a PPL split?', 'Yes. Six training days defaults toward push/pull/legs.'],
    ],
    related: ['weekly-volume-checker', 'exercise-swap-finder', 'smart-warm-up-calculator'],
  },
  {
    slug: 'exercise-swap-finder',
    type: 'swaps',
    name: 'Exercise Swap Finder',
    title: 'Exercise Swap Finder: Replace an Exercise Without Losing the Stimulus',
    metaDescription: 'Find smart exercise alternatives based on target muscle, equipment, fatigue, and training goal.',
    h1: 'Exercise Swap Finder',
    promise: 'Replace an exercise without losing the training intent.',
    intro: 'Most alternative lists are static. Jacked ranks swaps by why you need the swap: equipment, joint comfort, fatigue, or preference.',
    primaryKeyword: 'exercise alternatives',
    campaign: 'exercise_swap_finder',
    defaults: {
      exercise: 'barbell back squat',
      reason: 'too much fatigue',
      equipment: 'commercial gym',
      goal: 'less fatigue',
    },
    sections: [
      ['How the swap finder works', 'The tool starts with the original exercise, then ranks alternatives by target muscle, movement pattern, fatigue cost, equipment, and reason for swapping.'],
      ['Swap the exercise, not the goal', 'A good swap keeps the target muscle and effort close unless pain, equipment, or fatigue forces a bigger change.'],
      ['When to use a lower-fatigue swap', 'Use lower-fatigue options when the target muscle needs work but the original lift is creating too much systemic or joint cost.'],
      ['Common mistakes', 'Do not replace a hard compound with a random easy movement and expect the same stimulus. Match the intent.'],
    ],
    examples: [
      'Replace barbell back squat with leg press when you want similar quad stimulus and less axial fatigue.',
      'Replace bench press with dumbbell bench press when shoulder comfort is the reason for the swap.',
    ],
    faqs: [
      ['What is a good squat alternative?', 'Leg press, hack squat, front squat, and heel-elevated goblet squat can all work depending on equipment and reason.'],
      ['Should I swap exercises often?', 'Swap when there is a clear reason. Too much random variation makes progression harder to read.'],
    ],
    related: ['workout-split-builder', 'weekly-volume-checker', 'next-set-calculator'],
  },
  {
    slug: 'hevy-import-checker',
    type: 'hevy',
    name: 'Hevy Import Checker',
    title: 'Hevy Import Checker: Preview Your Workout History Before Importing',
    metaDescription: 'Preview your Hevy workout export locally in your browser and see how many workouts, sets, exercises, and measurements can be imported into Jacked.',
    h1: 'Hevy Import Checker',
    promise: 'Preview your Hevy export locally before switching.',
    intro: 'Upload or paste a Hevy CSV. The file is parsed in your browser. Nothing is uploaded, no account required, no server storage.',
    primaryKeyword: 'Hevy import',
    campaign: 'hevy_import_checker',
    defaults: {
      csvText: `Date,Exercise Name,Set Order,Weight,Reps
2026-01-01,Bench Press,1,80,10
2026-01-01,Bench Press,2,80,8
2026-01-03,Squat,1,120,5`,
    },
    sections: [
      ['Privacy implementation', 'This checker runs locally in your browser. The CSV is parsed client-side and is not sent to a server by this page.'],
      ['What the checker looks for', 'It counts workout dates, exercise names, set rows, and measurement-like columns to preview import shape.'],
      ['Why this is high intent', 'Someone with a workout export file is not browsing casually. They are evaluating migration.'],
      ['Common mistakes', 'Do not upload private training exports to tools that do not explain where the file goes. Local-only parsing is the right default.'],
    ],
    examples: [
      'A Hevy export with 214 workouts, 1,842 sets, and 86 exercises is a strong migration signal.',
      'If the checker sees exercise names and dated set rows, Jacked can make the import promise tangible before install.',
    ],
    faqs: [
      ['Is my Hevy CSV uploaded?', 'No. This page parses the CSV in your browser and does not upload it.'],
      ['What should I do after checking it?', 'Download Jacked and use the in-app import flow to bring over your history.'],
    ],
    related: ['next-set-calculator', 'weekly-volume-checker', 'workout-split-builder'],
  },
  {
    slug: 'strong-csv-import-checker',
    type: 'strong-import',
    name: 'Strong CSV Import Checker',
    title: 'Strong CSV Import Checker: Preview Your Workout History Before Importing',
    metaDescription: 'Check a Strong workout CSV locally in your browser before moving your training history into Jacked.',
    h1: 'Strong CSV Import Checker',
    promise: 'Preview a Strong export before you switch apps.',
    intro: 'Paste or upload a Strong CSV and see whether the file has the workout, exercise, set, load, rep, note, and effort fields Jacked can use.',
    primaryKeyword: 'Strong CSV import',
    campaign: 'strong_csv_import_checker',
    defaults: {
      csvText: `Date,Workout Name,Exercise Name,Set Order,Weight,Reps,Distance,Seconds,Notes
2026-01-01,Upper,Bench Press,1,80,10,,,
2026-01-01,Upper,Bench Press,2,80,8,,,
2026-01-02,Lower,Leg Press,1,200,12,,,`,
    },
    sections: [
      ['What this checker looks for', 'It checks dates, workout names, exercise names, set rows, loads, reps, notes, and effort columns so you can spot import problems before switching.'],
      ['Why Strong exports need review', 'Old logs often include custom exercises, missing units, blank rows, and unusual timed sets. Those details can split history or hide useful progress.'],
      ['Privacy implementation', 'The CSV is parsed in your browser. Nothing is uploaded by this web tool. Keep the original export untouched until your import is verified.'],
      ['Common mistakes', 'Do not edit your only copy of the export. Work from a duplicate and spot-check your main lifts after import.'],
    ],
    examples: [
      'A Strong export with workout dates, exercise names, set order, weight, and reps is usually import-ready enough to preview.',
      'If exercise names or dates are missing, fix those first. Those fields anchor history, routines, and progress charts.',
    ],
    faqs: [
      ['Is my Strong CSV uploaded?', 'No. This page parses the text in your browser and does not send it to a server.'],
      ['What should I check after import?', 'Open your main lifts, recent workouts, custom exercises, and notes before training from the imported history.'],
    ],
    related: ['workout-csv-validator', 'hevy-import-checker', 'next-set-calculator', 'weekly-volume-checker'],
  },
  {
    slug: 'workout-csv-validator',
    type: 'csv-validator',
    name: 'Workout CSV Validator',
    title: 'Workout CSV Validator for Lifting Apps',
    metaDescription: 'Validate workout CSV headers, missing values, mixed units, and likely import blockers before switching lifting apps.',
    h1: 'Workout CSV Validator',
    promise: 'Find workout CSV import blockers before they cost you history.',
    intro: 'Paste a workout export and get a practical readout: import-ready, review first, or fix before import.',
    primaryKeyword: 'workout CSV validator',
    campaign: 'workout_csv_validator',
    defaults: {
      csvText: `Date,Workout Name,Exercise Name,Set Order,Weight,Reps
2026-01-01,Upper,Bench Press,1,80,10
2026-01-01,Upper,Squat,2,120,5`,
    },
    sections: [
      ['What the validator checks', 'It checks for workout rows, date fields, exercise names, set rows, loads, reps, mixed units, and blank values that commonly break imports.'],
      ['Why validation matters', 'A CSV can look fine in a spreadsheet while still being hard for an app to import cleanly. Missing exercise names and dates are the biggest problems.'],
      ['How to use the result', 'Fix blockers first, review warnings second, then import a copy and spot-check your most important lifts.'],
      ['Common mistakes', 'Do not assume a successful upload means every workout mapped correctly. Check custom exercises and mixed-unit rows.'],
    ],
    examples: [
      'Missing exercise names: fix before import. Mixed kg/lb units: review before import. Clean dates and exercises: ready to test in the app.',
      'If only your recent clean rows import, your charts may look fine while older training quietly disappears.',
    ],
    faqs: [
      ['Can this validate any workout app export?', 'It checks common lifting CSV fields. App-specific formats can still need a dedicated import flow.'],
      ['Does this store my CSV?', 'No. The web tool parses the CSV locally in your browser.'],
    ],
    related: ['strong-csv-import-checker', 'hevy-import-checker', 'weekly-volume-checker', 'next-set-calculator'],
  },
  {
    slug: 'rest-time-calculator',
    type: 'rest-time',
    name: 'Rest Time Calculator',
    title: 'Rest Time Calculator: How Long to Rest Between Sets',
    metaDescription: 'Calculate a practical rest time from exercise type, goal, reps, RIR, set difficulty, and your next-set priority.',
    h1: 'Rest Time Calculator',
    promise: 'Get a rest target that protects the next set.',
    intro: 'Most rest advice gives a broad range. This tool turns the last set and next-set priority into a timer target.',
    primaryKeyword: 'rest time calculator',
    campaign: 'rest_time_calculator',
    defaults: {
      movementType: 'squat',
      goal: 'strength + size',
      reps: 6,
      rir: 1,
      lastSetDifficulty: 'grindy',
      nextSetPriority: 'load',
      timePressure: 'normal',
    },
    sections: [
      ['How the rest target is chosen', 'The calculator starts with your goal, then adjusts for exercise type, reps, RIR, set difficulty, next-set priority, and time pressure.'],
      ['When to rest longer', 'Rest longer when the lift is heavy, compound, close to failure, or when the next set needs load and rep quality.'],
      ['When to rest shorter', 'Rest shorter for isolation work, easier sets, endurance work, or when time is the limiting constraint.'],
      ['Common mistakes', 'Do not rush rest if it changes technique, cuts reps, or turns the wrong muscle into the limiter.'],
    ],
    examples: [
      'Heavy squat set, 6 reps at 1 RIR, next set needs load: rest about 4:00.',
      'Lateral raises, 15 reps at 2 RIR, hypertrophy priority: rest closer to 1:15-1:45 if performance holds.',
    ],
    faqs: [
      ['How long should I rest between sets?', 'Long enough that the next set can hit the intended reps, load, and target muscle without technique breaking down.'],
      ['Is shorter rest better for hypertrophy?', 'Not if it reduces useful hard reps. Short rest is a tool, not the goal.'],
    ],
    related: ['next-set-calculator', 'backoff-set-calculator', 'rir-calculator', 'smart-warm-up-calculator'],
  },
  {
    slug: 'backoff-set-calculator',
    type: 'backoff',
    name: 'Backoff Set Calculator',
    title: 'Backoff Set Calculator: Plan Volume After a Top Set',
    metaDescription: 'Use your top set, RIR, goal, fatigue, and readiness to calculate backoff set weights and reps.',
    h1: 'Backoff Set Calculator',
    promise: 'Turn a top set into useful backoff volume.',
    intro: 'Enter the top set. Get rounded backoff sets that keep volume hard enough to matter without turning every set into a grinder.',
    primaryKeyword: 'backoff set calculator',
    campaign: 'backoff_set_calculator',
    defaults: {
      units: 'kg',
      topSetWeight: 120,
      topSetReps: 5,
      topSetRir: 1,
      goal: 'strength + size',
      backoffSets: 3,
      backoffReps: 8,
      fatigue: 'normal',
      readiness: 'normal',
      increment: 2.5,
    },
    sections: [
      ['How backoff weight is calculated', 'The tool applies a top-set load drop based on goal, top-set effort, fatigue, readiness, and rounding increment.'],
      ['When to use bigger drops', 'Use a bigger drop after failure, high fatigue, poor readiness, or heavy low-rep top sets.'],
      ['When to use smaller drops', 'Use a smaller drop when the top set moved well and the goal is strength practice with crisp reps.'],
      ['Common mistakes', 'Do not turn every backoff into another top set. Backoffs should build quality volume after the heavy signal.'],
    ],
    examples: [
      'Top set: 120 kg x 5 @ 1 RIR. Backoff target: around 102.5 kg for 3 x 8.',
      'If the top set was a grind or readiness is poor, drop more load and keep reps clean.',
    ],
    faqs: [
      ['What percent should backoff sets use?', 'Many lifters land around a 10-20% drop, adjusted by goal, fatigue, and top-set difficulty.'],
      ['Are backoff sets for hypertrophy or strength?', 'Both. The top set gives a heavy signal; backoffs add repeatable volume.'],
    ],
    related: ['rest-time-calculator', 'rir-calculator', 'one-rep-max-calculator', 'next-set-calculator'],
  },
]

const exerciseSeeds = [
  {
    slug: 'bench-press',
    name: 'Bench Press',
    exercise: 'Bench press',
    movementType: 'horizontal press',
    equipment: 'barbell',
    units: 'kg',
    weight: 80,
    reps: 10,
    rir: 2,
    targetWeight: 100,
    targetReps: 8,
    progression: 'Bench usually progresses best with small jumps, stable pauses, and consistent grip width.',
    warmup: 'Bench warm-ups should groove the press path without tiring triceps before working sets.',
    mistake: 'Do not count touch-and-go reps one week and paused reps the next as the same signal.',
    alternatives: ['Dumbbell bench press', 'Machine chest press', 'Push-up'],
    swapExercise: 'bench press',
  },
  {
    slug: 'squat',
    name: 'Squat',
    exercise: 'Squat',
    movementType: 'squat',
    equipment: 'barbell',
    units: 'kg',
    weight: 120,
    reps: 8,
    rir: 2,
    targetWeight: 140,
    targetReps: 6,
    progression: 'Squat progress depends on depth, bracing, and repeatable bar path as much as load.',
    warmup: 'Squats usually deserve more ramping sets because the movement is heavy and skill-sensitive.',
    mistake: 'Do not add load when depth or brace quality changed enough to make the set incomparable.',
    alternatives: ['Leg press', 'Hack squat', 'Front squat'],
    swapExercise: 'barbell back squat',
  },
  {
    slug: 'deadlift',
    name: 'Deadlift',
    exercise: 'Deadlift',
    movementType: 'hinge',
    equipment: 'barbell',
    units: 'kg',
    weight: 160,
    reps: 5,
    rir: 2,
    targetWeight: 180,
    targetReps: 5,
    progression: 'Deadlift jumps should be conservative because fatigue cost rises faster than most lifts.',
    warmup: 'Deadlift warm-ups should ramp neural readiness without turning early sets into grinders.',
    mistake: 'Do not chase a heavier pull when speed, brace, or start position has clearly degraded.',
    alternatives: ['Romanian deadlift', 'Hip thrust', 'Back extension'],
    swapExercise: 'deadlift',
  },
  {
    slug: 'overhead-press',
    name: 'Overhead Press',
    exercise: 'Overhead press',
    movementType: 'vertical press',
    equipment: 'barbell',
    units: 'kg',
    weight: 50,
    reps: 8,
    rir: 2,
    targetWeight: 60,
    targetReps: 6,
    progression: 'Overhead press often needs smaller jumps than bench because loading tolerance is lower.',
    warmup: 'Press warm-ups should prepare shoulders and upper back without exhausting the prime movers.',
    mistake: 'Do not turn strict press progression into a lean-back push press without logging the change.',
    alternatives: ['Dumbbell shoulder press', 'Machine shoulder press', 'Landmine press'],
    swapExercise: 'bench press',
  },
  {
    slug: 'leg-press',
    name: 'Leg Press',
    exercise: 'Leg press',
    movementType: 'squat',
    equipment: 'machine',
    units: 'kg',
    weight: 220,
    reps: 12,
    rir: 2,
    targetWeight: 240,
    targetReps: 10,
    progression: 'Leg press progression works best when foot placement, depth, and sled setup stay consistent.',
    warmup: 'Leg press warm-ups can ramp quickly, but heavy targets still need enough knee and hip preparation.',
    mistake: 'Do not add plates by shortening range of motion.',
    alternatives: ['Hack squat', 'Back squat', 'Bulgarian split squat'],
    swapExercise: 'leg press',
  },
  {
    slug: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    exercise: 'Incline dumbbell press',
    movementType: 'horizontal press',
    equipment: 'dumbbell',
    units: 'kg',
    weight: 32.5,
    reps: 10,
    rir: 2,
    targetWeight: 35,
    targetReps: 8,
    progression: 'Incline dumbbell jumps are large, so adding reps before load is often the cleaner move.',
    warmup: 'Warm up the press and setup so the first working set is not limited by getting dumbbells into position.',
    mistake: 'Do not compare different bench angles as the same exercise progression.',
    alternatives: ['Incline machine press', 'Low-incline barbell press', 'Feet-up dumbbell press'],
    swapExercise: 'bench press',
  },
  {
    slug: 'lat-pulldown',
    name: 'Lat Pulldown',
    exercise: 'Lat pulldown',
    movementType: 'row / pull',
    equipment: 'cable',
    units: 'kg',
    weight: 70,
    reps: 12,
    rir: 2,
    targetWeight: 75,
    targetReps: 10,
    progression: 'Pulldown progression depends on consistent torso angle, grip, and bottom position.',
    warmup: 'Pulldowns usually need only a few ramping sets unless elbows or shoulders need more preparation.',
    mistake: 'Do not count heavier reps if the movement turns into a torso heave.',
    alternatives: ['Pull-up', 'Assisted pull-up', 'One-arm cable pulldown'],
    swapExercise: 'lat pulldown',
  },
  {
    slug: 'barbell-row',
    name: 'Barbell Row',
    exercise: 'Barbell row',
    movementType: 'row / pull',
    equipment: 'barbell',
    units: 'kg',
    weight: 80,
    reps: 10,
    rir: 2,
    targetWeight: 90,
    targetReps: 8,
    progression: 'Rows need strict torso and touch-point standards or load jumps become hard to interpret.',
    warmup: 'Row warm-ups should prepare the hinge position as well as the upper back pull.',
    mistake: 'Do not trade range and torso control for load unless the variation is intentionally changed.',
    alternatives: ['Chest-supported row', 'Cable row', 'One-arm dumbbell row'],
    swapExercise: 'lat pulldown',
  },
  {
    slug: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    exercise: 'Romanian deadlift',
    movementType: 'hinge',
    equipment: 'barbell',
    units: 'kg',
    weight: 100,
    reps: 10,
    rir: 2,
    targetWeight: 115,
    targetReps: 8,
    progression: 'RDL progression should preserve hamstring tension, hip position, and controlled eccentrics.',
    warmup: 'RDL warm-ups should establish hinge range before load gets heavy.',
    mistake: 'Do not add weight by turning the lift into a shorter-range conventional deadlift.',
    alternatives: ['Dumbbell RDL', 'Seated leg curl', 'Good morning'],
    swapExercise: 'deadlift',
  },
  {
    slug: 'lateral-raise',
    name: 'Lateral Raise',
    exercise: 'Lateral raise',
    movementType: 'isolation',
    equipment: 'dumbbell',
    units: 'kg',
    weight: 12.5,
    reps: 15,
    rir: 2,
    targetWeight: 15,
    targetReps: 12,
    progression: 'Lateral raises usually progress better with reps and control before load jumps.',
    warmup: 'Most lateral raise sessions need little warm-up beyond a light activation set.',
    mistake: 'Do not add load by turning strict raises into momentum swings.',
    alternatives: ['Cable lateral raise', 'Machine lateral raise', 'Lean-away dumbbell lateral raise'],
    swapExercise: 'lateral raise',
  },
]

function exerciseTool(seed, kind) {
  const baseDefaults = {
    exercise: seed.exercise,
    units: seed.units,
    weight: seed.weight,
    reps: seed.reps,
    rir: seed.rir,
    increment: seed.units === 'kg' ? 2.5 : 5,
  }

  if (kind === 'next-set') {
    return {
      slug: `${seed.slug}-next-set-calculator`,
      type: 'next-set',
      name: `${seed.name} Next Set Calculator`,
      title: `${seed.name} Next Set Calculator`,
      metaDescription: `Enter your last ${seed.name.toLowerCase()} set and get a practical next target based on reps, RIR, and your target rep range.`,
      h1: `${seed.name} Next Set Calculator`,
      promise: `Enter your last ${seed.name.toLowerCase()} set and get your next target.`,
      intro: `${seed.progression} Jacked turns the set into a clear next move.`,
      primaryKeyword: `${seed.name.toLowerCase()} next set calculator`,
      campaign: `${seed.slug.replaceAll('-', '_')}_next_set_calculator`,
      exerciseSpecific: true,
      defaults: {
        ...baseDefaults,
        minReps: seed.reps >= 10 ? 10 : 6,
        maxReps: seed.reps >= 10 ? 12 : 8,
        targetRir: 2,
        goal: 'hypertrophy',
        equipment: seed.equipment,
      },
      sections: [
        [`How Jacked chooses your next ${seed.name.toLowerCase()} set`, `The calculator reads load, reps, and RIR, then applies ${seed.name.toLowerCase()}-specific progression context. ${seed.progression}`],
        ['When to add weight', `Add load when you hit the top of the target range at the planned RIR without changing the ${seed.name.toLowerCase()} standard.`],
        ['When to add reps instead', `If the load jump is large or reps are still inside range, keep the same ${seed.name.toLowerCase()} weight and add reps first.`],
        ['Common mistake', seed.mistake],
      ],
      examples: [
        `Last set: ${seed.weight} ${seed.units} x ${seed.reps} @ ${seed.rir} RIR. Recommendation: add the smallest useful jump only if execution matched your normal ${seed.name.toLowerCase()} standard.`,
        `If reps are inside the range, hold ${seed.weight} ${seed.units} and chase one cleaner rep before adding load.`,
      ],
      faqs: [
        [`What should I lift next for ${seed.name.toLowerCase()}?`, 'Use the smallest load jump when reps, RIR, and execution all support it. Otherwise add reps or hold load.'],
        [`Why does RIR matter for ${seed.name.toLowerCase()}?`, 'RIR separates a repeatable progression signal from a set that only succeeded because effort spiked.'],
      ],
      related: ['next-set-calculator', 'smart-warm-up-calculator', 'one-rep-max-calculator'],
    }
  }

  if (kind === 'warmup') {
    return {
      slug: `${seed.slug}-warm-up-calculator`,
      type: 'warmup',
      name: `${seed.name} Warm-Up Calculator`,
      title: `${seed.name} Warm-Up Calculator`,
      metaDescription: `Generate ${seed.name.toLowerCase()} warm-up sets from your target working weight, reps, and recent heavy exposure.`,
      h1: `${seed.name} Warm-Up Calculator`,
      promise: `Build a warm-up path for your ${seed.name.toLowerCase()} working weight.`,
      intro: seed.warmup,
      primaryKeyword: `${seed.name.toLowerCase()} warm up calculator`,
      campaign: `${seed.slug.replaceAll('-', '_')}_warm_up_calculator`,
      exerciseSpecific: true,
      defaults: {
        exercise: seed.exercise,
        movementType: seed.movementType,
        units: seed.units,
        targetWeight: seed.targetWeight,
        targetReps: seed.targetReps,
        increment: seed.units === 'kg' ? 2.5 : 5,
        lastExposure: seed.movementType === 'isolation' ? '1-3 days' : '4-7 days',
        status: 'normal',
        preference: seed.movementType === 'isolation' ? 'minimal' : 'standard',
      },
      sections: [
        [`How ${seed.name.toLowerCase()} warm-ups work`, seed.warmup],
        ['When to add a warm-up set', 'Add one ramping set when the target is heavier than usual, the last heavy exposure was over a week ago, or you feel cautious.'],
        ['When to keep it minimal', 'Use fewer warm-ups when the lift is light, familiar, or isolation-focused and joints feel ready.'],
        ['Common mistake', seed.mistake],
      ],
      examples: [
        `Target: ${seed.targetWeight} ${seed.units} x ${seed.targetReps}. The calculator builds ramping sets that prepare the lift without stealing working-set performance.`,
        `If your last heavy ${seed.name.toLowerCase()} exposure was over a week ago, use the more thorough path.`,
      ],
      faqs: [
        [`How many warm-up sets for ${seed.name.toLowerCase()}?`, 'Use enough ramping sets to make the working weight feel familiar without accumulating fatigue.'],
        ['Should warm-ups be hard?', 'No. They should prepare the lift and leave reps in reserve.'],
      ],
      related: ['smart-warm-up-calculator', `${seed.slug}-next-set-calculator`, 'plate-calculator'],
    }
  }

  if (kind === 'one-rm') {
    return {
      slug: `${seed.slug}-1rm-calculator`,
      type: 'one-rm',
      name: `${seed.name} 1RM Calculator`,
      title: `${seed.name} 1RM Calculator`,
      metaDescription: `Estimate your ${seed.name.toLowerCase()} one-rep max from weight, reps, and optional RIR, then get a useful training target.`,
      h1: `${seed.name} 1RM Calculator`,
      promise: `Estimate your ${seed.name.toLowerCase()} max and get a useful target.`,
      intro: `A ${seed.name.toLowerCase()} e1RM is useful when the set standard is consistent. ${seed.mistake}`,
      primaryKeyword: `${seed.name.toLowerCase()} 1RM calculator`,
      campaign: `${seed.slug.replaceAll('-', '_')}_1rm_calculator`,
      exerciseSpecific: true,
      defaults: {
        ...baseDefaults,
        formula: 'jacked',
      },
      sections: [
        [`What ${seed.name.toLowerCase()} e1RM means`, `This is a ballpark estimate from a submaximal ${seed.name.toLowerCase()} set, not a guaranteed max attempt.`],
        ['Why RIR improves the estimate', 'The same reps at different effort levels imply different strength. RIR makes the estimate more useful.'],
        ['Best data for this lift', `Use recent sets where ${seed.name.toLowerCase()} execution matched your normal standard.`],
        ['Common mistake', seed.mistake],
      ],
      examples: [
        `${seed.weight} ${seed.units} x ${seed.reps} @ ${seed.rir} RIR estimates max strength and a practical 8-rep target.`,
        `If the set was unusually sloppy, treat the ${seed.name.toLowerCase()} e1RM as lower confidence.`,
      ],
      faqs: [
        [`Is this ${seed.name.toLowerCase()} 1RM exact?`, 'No. It is a training estimate. Use it for trends and targets, not as proof of a tested max.'],
        ['Should I test a true 1RM?', 'Only when it fits your goal, skill, and recovery. Most hypertrophy training does not require frequent max testing.'],
      ],
      related: ['one-rep-max-calculator', `${seed.slug}-next-set-calculator`, `${seed.slug}-warm-up-calculator`],
    }
  }

  if (kind === 'strength-level') {
    return {
      slug: `${seed.slug}-strength-level-calculator`,
      type: 'strength-level',
      name: `${seed.name} Strength Level Calculator`,
      title: `${seed.name} Strength Level Calculator: Compare by Bodyweight`,
      metaDescription: `Compare your ${seed.name.toLowerCase()} strength level by bodyweight from weight, reps, and RIR, then see the next benchmark to chase.`,
      h1: `${seed.name} Strength Level Calculator`,
      promise: `Compare your ${seed.name.toLowerCase()} by bodyweight and get the next benchmark.`,
      intro: `${seed.progression} This page estimates your strength tier, then shows the practical gap to the next level.`,
      primaryKeyword: `${seed.name.toLowerCase()} strength level calculator`,
      campaign: `${seed.slug.replaceAll('-', '_')}_strength_level_calculator`,
      exerciseSpecific: true,
      defaults: {
        exercise: seed.exercise,
        units: seed.units,
        sex: 'male',
        age: 29,
        bodyweight: seed.slug === 'lateral-raise' ? 75 : 82,
        liftWeight: seed.weight,
        reps: seed.reps,
        rir: seed.rir,
        increment: seed.units === 'kg' ? 2.5 : 5,
      },
      sections: [
        [`How the ${seed.name.toLowerCase()} strength level is calculated`, `The calculator estimates ${seed.name.toLowerCase()} e1RM from weight, reps, and RIR, divides it by bodyweight, then compares that ratio with transparent Jacked standards.`],
        ['Why bodyweight matters', 'A lift means something different at different bodyweights. Ratio-based standards make the comparison more useful than the raw number alone.'],
        ['How to use the next benchmark', `Use the next ${seed.name.toLowerCase()} tier as a block-level target, then let normal progression, RIR, and execution decide each workout.`],
        ['Common mistake', seed.mistake],
      ],
      examples: [
        `${seed.name}: ${seed.weight} ${seed.units} x ${seed.reps} @ ${seed.rir} RIR estimates your current tier and the gap to the next bodyweight-based benchmark.`,
        `If the gap is small, a focused ${seed.name.toLowerCase()} block may be enough. If the gap is large, build reps and execution first.`,
      ],
      faqs: [
        [`What is a good ${seed.name.toLowerCase()} strength level?`, 'A good level depends on sex, bodyweight, training age, technique standard, and whether the lift is a main goal.'],
        ['Are these official standards?', 'No. They are practical Jacked standards for training decisions, not federation records or copied user-population rankings.'],
      ],
      related: ['strength-level-calculator', `${seed.slug}-next-set-calculator`, `${seed.slug}-1rm-calculator`],
    }
  }

  return {
    slug: `${seed.slug}-alternatives`,
    type: 'swaps',
    name: `${seed.name} Alternatives`,
    title: `${seed.name} Alternatives: Smart Exercise Swaps`,
    metaDescription: `Find ${seed.name.toLowerCase()} alternatives based on equipment, joint comfort, fatigue, and training goal.`,
    h1: `${seed.name} Alternatives`,
    promise: `Replace ${seed.name.toLowerCase()} without losing the stimulus.`,
    intro: `A good ${seed.name.toLowerCase()} alternative keeps the training intent clear: target muscle, range, effort, and fatigue cost.`,
    primaryKeyword: `${seed.name.toLowerCase()} alternatives`,
    campaign: `${seed.slug.replaceAll('-', '_')}_alternatives`,
    exerciseSpecific: true,
    defaults: {
      exercise: seed.swapExercise,
      reason: 'too much fatigue',
      equipment: 'commercial gym',
      goal: 'less fatigue',
    },
    sections: [
      [`How to replace ${seed.name.toLowerCase()}`, `Start with the reason for the swap, then choose an option that keeps the target stimulus. Good options include ${seed.alternatives.join(', ')}.`],
      ['When to choose a lower-fatigue swap', 'Use lower-fatigue swaps when the target muscle needs work but the original lift is driving too much systemic or joint cost.'],
      ['When to keep the original lift', 'Keep it when performance is improving, joints feel fine, and equipment is available.'],
      ['Common mistake', seed.mistake],
    ],
    examples: [
      `If ${seed.name.toLowerCase()} is unavailable, choose the closest option that matches your goal: ${seed.alternatives[0]}.`,
      `If fatigue is the problem, pick the swap that preserves the muscle stimulus with less setup or systemic cost.`,
    ],
    faqs: [
      [`What is the best ${seed.name.toLowerCase()} alternative?`, `It depends on why you are swapping. Common options include ${seed.alternatives.join(', ')}.`],
      ['Should I use the same reps?', 'Usually start with the same rep range and RIR, then adjust after one or two sessions.'],
    ],
    related: ['exercise-swap-finder', 'next-set-calculator', 'workout-split-builder'],
  }
}

const nextSetExerciseSlugs = ['bench-press', 'squat', 'deadlift', 'overhead-press', 'leg-press', 'incline-dumbbell-press', 'lat-pulldown', 'barbell-row', 'romanian-deadlift']
const warmupExerciseSlugs = ['bench-press', 'squat', 'deadlift', 'overhead-press']
const oneRmExerciseSlugs = ['bench-press', 'squat', 'deadlift', 'overhead-press', 'leg-press', 'lat-pulldown', 'barbell-row', 'romanian-deadlift']
const strengthLevelExerciseSlugs = ['bench-press', 'squat', 'deadlift', 'overhead-press', 'leg-press', 'lat-pulldown', 'barbell-row', 'romanian-deadlift']
const alternativeExerciseSlugs = ['bench-press', 'squat', 'deadlift', 'leg-press', 'lat-pulldown', 'lateral-raise']
const exerciseSeedMap = Object.fromEntries(exerciseSeeds.map((seed) => [seed.slug, seed]))

export const exerciseSpecificTools = [
  ...nextSetExerciseSlugs.map((slug) => exerciseTool(exerciseSeedMap[slug], 'next-set')),
  ...warmupExerciseSlugs.map((slug) => exerciseTool(exerciseSeedMap[slug], 'warmup')),
  ...oneRmExerciseSlugs.map((slug) => exerciseTool(exerciseSeedMap[slug], 'one-rm')),
  ...strengthLevelExerciseSlugs.map((slug) => exerciseTool(exerciseSeedMap[slug], 'strength-level')),
  ...alternativeExerciseSlugs.map((slug) => exerciseTool(exerciseSeedMap[slug], 'alternatives')),
]

export const tools = [...coreTools, ...exerciseSpecificTools]

export const toolMap = Object.fromEntries(tools.map((tool) => [tool.slug, tool]))

export function appStoreUrl(campaign, content = 'tool_cta') {
  return `${APP_STORE_BASE}?utm_source=jacked_coach&utm_medium=tool&utm_campaign=${campaign}&utm_content=${content}`
}
